test: validity for gate, job_type, measure, noise, pauli_string and other_instructions
ColibrITD-SAS/mpqp pull request #106
Opened 2024-11-18 13:41 UTC by JulienCalistoTD

…nstr

2024-11-18 15:31 UTC, Henri-ColibrITD commented on mpqp/tools/circuit.py
> +        prob = rng.uniform(0, 1)
I'm not in love with this, I guess this is the reason why you asked if we couldn't have a `proba` attribute for all noises

2024-11-18 15:32 UTC, Henri-ColibrITD commented on tests/execution/test_validity.py
> +other_instr = [
I would have that as a fixture

2024-11-18 15:32 UTC, Henri-ColibrITD commented on tests/execution/test_validity.py
> +pauli_strings = [Ip @ Xp @ Yp @ Zp, Xp + Zp, Yp]
fixture

2024-11-18 15:35 UTC, Henri-ColibrITD requested changes
tiny tweaks

2024-11-19 14:20 UTC, JulienCalistoTD commented on tests/execution/test_validity.py
> +other_instr = [
done

2024-11-19 14:20 UTC, JulienCalistoTD commented on tests/execution/test_validity.py
> +pauli_strings = [Ip @ Xp @ Yp @ Zp, Xp + Zp, Yp]
done

2024-11-20 14:39 UTC, merged