feat: dynamic circuit, and fix VariableSizeBasis
ColibrITD-SAS/mpqp pull request #120
Opened 2024-12-17 13:25 UTC by JulienCalistoTD

2024-12-27 14:53 UTC, hJaffaliColibritd commented on mpqp/core/circuit.py
> +            if any(conn >= self.nb_qubits for conn in components.connections()):
Since `self._user_nb_qubits is not None`, you can directly use `self._user_nb_qubits` instead of calling the property `self.nb_qubits`

2024-12-30 02:46 UTC, hJaffaliColibritd reviewed
Good and important work.
Should we add more tests for Basis/VariableSizeBasis ?

2024-12-30 02:46 UTC, hJaffaliColibritd commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
If you call the property `self.nb_qubits`, then this check is already done there, so you can directly use the property for the repr no ?

2024-12-30 02:46 UTC, hJaffaliColibritd commented on mpqp/core/instruction/measurement/basis.py
> +        >>> circ.add(BasisMeasure([0, 1, 2], basis=custom_basis, shots=10000))
We can also remove the targets here in `BasisMeasure`

2024-12-30 02:46 UTC, hJaffaliColibritd commented on mpqp/core/instruction/measurement/basis.py
> +        Bn = reduce(np.kron, [self.basis_vectors] * nb_qubits, np.eye(1))
chipotage: maybe add a condition that, when the number of qubits is already matching the size of basis vector, we don't need to perform all the steps below (typically when we call `set_size` in the __init__)

2024-12-30 02:46 UTC, hJaffaliColibritd commented on mpqp/tools/display.py
> +        list[complex | float | int] | npt.NDArray[np.complex64 | np.float32 | np.int32]
Maybe instead of putting `complex | float | int`, we can use the class `Complex` from the package `numbers`?

2025-01-02 12:40 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
>          self._nb_qubits = nb_qubits
maybe for efficiency sake we can check if it was not already the same before, and if so we do nothing ?

2025-01-02 12:42 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
> +            return f'QCircuit([{instructions_repr}, {noise_repr}]{nb_qubits}, nb_cbits={self.nb_cbits}, label="{self.label}")'
if no noise we would get an comma trailing list here, and if no instruction too we would get the invalid syntax `[,]` I believe

2025-01-02 12:43 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
> +            return f'QCircuit([{instructions_repr}, {noise_repr}]{nb_qubits}, nb_cbits={self.nb_cbits}, label="{self.label}")'
we should only display the comma between intrs and noises if noises are not empty

2025-01-02 12:49 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
>          if self.noises:
I would to something like 
```py
components = instructions_repr + ("" if self.noises is None else (", " + ", ".join(map(repr, self.noises))))
return f'QCircuit([components]{nb_qubits}, nb_cbits={self.nb_cbits}, label="{self.label}")'
```

2025-01-02 12:51 UTC, Henri-ColibrITD commented on mpqp/core/instruction/measurement/basis.py
> +    Example:
very nice

2025-01-02 12:56 UTC, Henri-ColibrITD commented on mpqp/tools/display.py
> +        list[complex | float | int] | npt.NDArray[np.complex64 | np.float32 | np.int32]
In theory I agree, in practice I had many problems with the abstract number types, but it would be cool if it worked (to try anyway ?)

2025-01-02 12:58 UTC, Henri-ColibrITD requested changes
see comments

2025-01-15 12:55 UTC, JulienCalistoTD commented on mpqp/core/circuit.py
> +            if any(conn >= self.nb_qubits for conn in components.connections()):
changed _user_nb_qubits to nb_qubits

2025-01-27 09:46 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
>          self._nb_qubits = nb_qubits
was this taken into account ?

2025-01-27 10:05 UTC, Henri-ColibrITD commented on mpqp/tools/display.py
> +        list[complex | float | int] | npt.NDArray[np.complex64 | np.float32 | np.int32]
have you checked it indeed works in many different contexts ?

2025-01-27 10:13 UTC, Henri-ColibrITD commented on mpqp/tools/display.py
> +        list[complex | float | int] | npt.NDArray[np.complex64 | np.float32 | np.int32]
haaaa you defined your own complex type, I didn't notice, have you discussed this choice with Hamza ? I don't know how to feel about it (on one hand, it makes the code more readable here, but since it's not used anywhere else, maybe an overcomplication ? and on the other hand, since it's the same name as a "standard class" -- `numbers.Complex`, it may be confusing)

2025-01-27 10:17 UTC, Henri-ColibrITD commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
taking this into account ?

2025-01-27 10:53 UTC, Henri-ColibrITD commented on tests/core/instruction/measurement/test_basis.py
I didn't see a reply on this comment:
https://github.com/ColibrITD-SAS/mpqp/pull/120#pullrequestreview-2525114520

2025-01-27 10:54 UTC, Henri-ColibrITD reviewed
it would be good to reply to all comments, but we're very close to merge now

2025-01-28 09:24 UTC, JulienCalistoTD commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
```py
    @property
    def nb_qubits(self) -> int:
        """Number of qubits of the circuit."""
        return self._nb_qubits if self._user_nb_qubits is None else self._user_nb_qubits
```
Yes, self.nb_qubits will always return a value even if self._user_nb_qubits is None, but that's not what we wanted to check. We want to know if the circuit is dynamic, so if self._user_nb_qubits is None

2025-01-28 10:07 UTC, JulienCalistoTD commented on mpqp/tools/display.py
> +        list[complex | float | int] | npt.NDArray[np.complex64 | np.float32 | np.int32]
Finally it works with the `Complex` class from the `numbers` package, so I removed my class. This is better

2025-01-28 10:17 UTC, JulienCalistoTD commented on mpqp/core/circuit.py
>          self._nb_qubits = nb_qubits
add check : 
```py
    if self._user_nb_qubits is None or self._user_nb_qubits != nb_qubits:
```

2025-01-28 16:15 UTC, JulienCalistoTD commented on tests/core/instruction/measurement/test_basis.py
i add some test for VariableSizeBasis and allows basis_vectors of any size and set_size only on multiple of basis_vectors.

2025-02-04 13:15 UTC, hJaffaliColibritd commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
I still don't get it. Indeed here you check if the circuit is dynamic, but inside the if, you only call self.nb_qubits, that will check again if the circuit is dynamic and return the right value.

What you mean is that you want nb_qubits to stay the empty string if the circuit is dynamic, and otherwise print the self._user_nb_qubits?

2025-02-05 09:49 UTC, JulienCalistoTD commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
Yes, if the circuit is dynamic, we want to create a dynamic circuit from repr, so we must not specify a number of qubits, nb_circuit should not be initialized.

2025-02-05 13:14 UTC, hJaffaliColibritd commented on mpqp/core/circuit.py
> +        if self._user_nb_qubits is not None:
Ok thanks

2025-02-05 13:16 UTC, hJaffaliColibritd approved these changes

2025-02-05 14:00 UTC, merged