Fix cirq obs variance
ColibrITD-SAS/mpqp pull request #69
Opened 2024-07-02 10:59 UTC by JulienCalistoTD

2024-07-11 09:44 UTC, JulienCalistoTD commented
write some test

2024-07-12 08:04 UTC, Henri-ColibrITD commented on mpqp/core/instruction/measurement/pauli_string.py
> +        if isinstance(pauli, (CirqPauliSum, CirqPauliString)):
is the max useful ? since you already checked that `nb_qubits == 0`

2024-07-12 08:05 UTC, Henri-ColibrITD commented on mpqp/core/instruction/measurement/pauli_string.py
> +    ) -> PauliString | List[PauliString]:
why do we need to pass a list of PS ?

2024-07-12 08:23 UTC, Henri-ColibrITD commented on mpqp/core/instruction/measurement/pauli_string.py
> +            pauli: The pauli object(s) to be converted. This can be a single CirqPauliSum, a single CirqPauliString, or a list of CirqPauliString objects.
no need to list the input types on the doc

2024-07-12 09:28 UTC, Henri-ColibrITD commented on mpqp/core/instruction/measurement/pauli_string.py
> +    ) -> PauliString | List[PauliString]:
we could also add PS from other SDKs but put them behind an `NotImplementedError`

2024-07-12 14:11 UTC, Henri-ColibrITD requested changes
some questions to be answered

2024-07-25 12:43 UTC, Henri-ColibrITD approved these changes

2024-07-25 12:43 UTC, merged